# Generated by Django 3.2.9 on 2022-03-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220307_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailywh',
            options={'verbose_name': 'Kunlik ish soati', 'verbose_name_plural': 'Kunlik ish soati'},
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['date'], 'verbose_name': 'Sana', 'verbose_name_plural': 'Sana'},
        ),
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.ManyToManyField(through='main.DailyWH', to='main.Date'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
    ]
